export interface DeviceSeed {
  category_slug: string;
  slug: string;
  name: string;
  brand: string;
  model_year: number | null;
  model_file: string | null;
  thumbnail_url: string | null;
  description: string;
  common_issues: string[];
  is_popular: boolean;
}

export const devices: DeviceSeed[] = [
  // ── GAMING CONTROLLERS ──────────────────────────────────────────
  {
    category_slug: "gaming-controllers",
    slug: "ps5-dualsense",
    name: "PS5 DualSense Controller",
    brand: "Sony",
    model_year: 2020,
    model_file: null,
    thumbnail_url: null,
    description: "The PS5 DualSense is Sony's haptic feedback controller featuring adaptive triggers and a built-in microphone.",
    common_issues: ["Stick drift", "Adaptive trigger not working", "USB-C charging port loose", "Touchpad not responding", "Speaker crackling", "Battery draining fast"],
    is_popular: true,
  },
  {
    category_slug: "gaming-controllers",
    slug: "ps5-dualsense-edge",
    name: "PS5 DualSense Edge Controller",
    brand: "Sony",
    model_year: 2023,
    model_file: null,
    thumbnail_url: null,
    description: "The DualSense Edge is Sony's pro controller with swappable stick modules and rear buttons.",
    common_issues: ["Stick module worn out", "Rear button not registering", "Profile not saving", "USB-C port damage"],
    is_popular: false,
  },
  {
    category_slug: "gaming-controllers",
    slug: "ps4-dualshock-4",
    name: "PS4 DualShock 4",
    brand: "Sony",
    model_year: 2013,
    model_file: null,
    thumbnail_url: null,
    description: "The DualShock 4 is Sony's PS4 controller with a touchpad, Share button, and light bar.",
    common_issues: ["Stick drift", "Micro-USB port loose", "L2/R2 trigger broken", "Light bar not turning on", "Battery not charging", "Share button stuck"],
    is_popular: true,
  },
  {
    category_slug: "gaming-controllers",
    slug: "xbox-series-x-controller",
    name: "Xbox Series X/S Controller",
    brand: "Microsoft",
    model_year: 2020,
    model_file: null,
    thumbnail_url: null,
    description: "The Xbox Series X/S controller features a textured grip, Share button, and USB-C connectivity.",
    common_issues: ["Stick drift", "Bumper button not clicking", "USB-C port damage", "D-pad feels mushy", "Trigger rumble not working", "Wireless disconnecting"],
    is_popular: true,
  },
  {
    category_slug: "gaming-controllers",
    slug: "xbox-one-controller",
    name: "Xbox One Controller",
    brand: "Microsoft",
    model_year: 2013,
    model_file: null,
    thumbnail_url: null,
    description: "The original Xbox One controller with a micro-USB port and standard layout.",
    common_issues: ["Stick drift", "Micro-USB port broken", "Bumper button loose", "A/B/X/Y button sticky", "Battery cover missing"],
    is_popular: false,
  },
  {
    category_slug: "gaming-controllers",
    slug: "xbox-360-controller",
    name: "Xbox 360 Controller",
    brand: "Microsoft",
    model_year: 2005,
    model_file: null,
    thumbnail_url: null,
    description: "The classic Xbox 360 wired or wireless controller.",
    common_issues: ["Stick drift", "D-pad unresponsive", "Guide button not lighting up", "Trigger spring broken", "AA battery connection corroded"],
    is_popular: false,
  },
  {
    category_slug: "gaming-controllers",
    slug: "nintendo-switch-pro-controller",
    name: "Nintendo Switch Pro Controller",
    brand: "Nintendo",
    model_year: 2017,
    model_file: null,
    thumbnail_url: null,
    description: "The Switch Pro Controller is Nintendo's premium controller with gyroscope and NFC.",
    common_issues: ["Stick drift", "USB-C charging intermittent", "Gyroscope drift", "Home button light not working", "D-pad not registering"],
    is_popular: true,
  },
  {
    category_slug: "gaming-controllers",
    slug: "joy-con-left",
    name: "Joy-Con (Left)",
    brand: "Nintendo",
    model_year: 2017,
    model_file: null,
    thumbnail_url: null,
    description: "The left Joy-Con for Nintendo Switch featuring stick, buttons, and accelerometer.",
    common_issues: ["Stick drift", "SL/SR button not working", "Rail connector loose", "Wrist strap connector broken", "Charging not working when attached"],
    is_popular: true,
  },
  {
    category_slug: "gaming-controllers",
    slug: "joy-con-right",
    name: "Joy-Con (Right)",
    brand: "Nintendo",
    model_year: 2017,
    model_file: null,
    thumbnail_url: null,
    description: "The right Joy-Con for Nintendo Switch featuring NFC, IR camera, and HD rumble.",
    common_issues: ["Stick drift", "NFC reader not working", "IR camera broken", "HD rumble not working", "SL/SR button unresponsive"],
    is_popular: true,
  },
  {
    category_slug: "gaming-controllers",
    slug: "gamecube-controller",
    name: "GameCube Controller",
    brand: "Nintendo",
    model_year: 2001,
    model_file: null,
    thumbnail_url: null,
    description: "Nintendo's iconic GameCube controller, still widely used for Super Smash Bros.",
    common_issues: ["C-stick drift", "L/R trigger spring broken", "A button mushy", "Cable fraying near controller", "Z button sticking"],
    is_popular: false,
  },
  {
    category_slug: "gaming-controllers",
    slug: "steam-deck",
    name: "Steam Deck",
    brand: "Valve",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Valve's portable PC gaming handheld with touchpads, gyroscope, and a full Linux OS.",
    common_issues: ["Trackpad not clicking", "Joystick drift", "USB-C port damage", "Battery swelling", "Screen flickering", "Fan loud or clicking"],
    is_popular: true,
  },
  {
    category_slug: "gaming-controllers",
    slug: "steam-controller",
    name: "Steam Controller",
    brand: "Valve",
    model_year: 2015,
    model_file: null,
    thumbnail_url: null,
    description: "Valve's unique controller with dual trackpads and a single analog stick.",
    common_issues: ["Trackpad haptic weak", "Battery contacts corroded", "Bumper button cracked", "Wireless dongle lost", "Back paddle not registering"],
    is_popular: false,
  },
  {
    category_slug: "gaming-controllers",
    slug: "razer-wolverine-v2",
    name: "Razer Wolverine V2",
    brand: "Razer",
    model_year: 2021,
    model_file: null,
    thumbnail_url: null,
    description: "Razer's wired Xbox-compatible pro controller with hair-trigger locks and multi-function buttons.",
    common_issues: ["Hair-trigger lock stiff", "Multi-function button not mapped", "Cable fraying", "Stick module worn", "Bumper button click feels off"],
    is_popular: false,
  },
  {
    category_slug: "gaming-controllers",
    slug: "8bitdo-sn30-pro",
    name: "8BitDo SN30 Pro",
    brand: "8BitDo",
    model_year: 2018,
    model_file: null,
    thumbnail_url: null,
    description: "8BitDo's retro-inspired Bluetooth controller compatible with Switch, Android, and PC.",
    common_issues: ["Bluetooth pairing fails", "Analog stick drift", "Start button sticking", "Battery door loose", "Rumble weak"],
    is_popular: false,
  },
  {
    category_slug: "gaming-controllers",
    slug: "logitech-f310",
    name: "Logitech F310 Gamepad",
    brand: "Logitech",
    model_year: 2010,
    model_file: null,
    thumbnail_url: null,
    description: "Logitech's budget wired USB gamepad for PC gaming.",
    common_issues: ["D-pad unresponsive", "Analog stick stiff", "USB cable fraying", "Mode button light not switching", "Trigger sticking"],
    is_popular: false,
  },
  {
    category_slug: "gaming-controllers",
    slug: "logitech-f710",
    name: "Logitech F710 Wireless Gamepad",
    brand: "Logitech",
    model_year: 2010,
    model_file: null,
    thumbnail_url: null,
    description: "Logitech's wireless gamepad with nano receiver and vibration feedback.",
    common_issues: ["Wireless connection dropping", "Vibration motor dead", "AA battery drain fast", "Nano receiver lost", "Bumper button cracked"],
    is_popular: false,
  },
  {
    category_slug: "gaming-controllers",
    slug: "powera-enhanced-controller",
    name: "PowerA Enhanced Wired Controller",
    brand: "PowerA",
    model_year: 2020,
    model_file: null,
    thumbnail_url: null,
    description: "PowerA's budget Xbox-licensed wired controller with programmable buttons.",
    common_issues: ["Stick drift", "Programmable buttons not saving", "USB cable breaking at junction", "Bumper button plastic cracking"],
    is_popular: false,
  },

  // ── PHONES ───────────────────────────────────────────────────────
  {
    category_slug: "phones",
    slug: "iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "Apple",
    model_year: 2023,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's flagship phone with titanium frame, A17 Pro chip, and USB-C.",
    common_issues: ["Screen cracked", "Battery draining fast", "Camera lens scratched", "USB-C port not charging", "Overheating", "Action Button not responding"],
    is_popular: true,
  },
  {
    category_slug: "phones",
    slug: "iphone-15",
    name: "iPhone 15",
    brand: "Apple",
    model_year: 2023,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's standard iPhone 15 with Dynamic Island and USB-C.",
    common_issues: ["Cracked screen", "Battery health degraded", "USB-C port debris", "Rear glass cracked", "Speaker muffled"],
    is_popular: true,
  },
  {
    category_slug: "phones",
    slug: "iphone-14",
    name: "iPhone 14",
    brand: "Apple",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's iPhone 14 with Emergency SOS via satellite and crash detection.",
    common_issues: ["Cracked screen", "Battery draining fast", "Lightning port not charging", "Rear glass broken", "Face ID not working"],
    is_popular: true,
  },
  {
    category_slug: "phones",
    slug: "iphone-13",
    name: "iPhone 13",
    brand: "Apple",
    model_year: 2021,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's iPhone 13 with improved battery and smaller notch.",
    common_issues: ["Cracked screen", "Battery swelling", "Lightning port damaged", "Camera module loose", "Microphone not working"],
    is_popular: false,
  },
  {
    category_slug: "phones",
    slug: "samsung-galaxy-s24",
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    model_year: 2024,
    model_file: null,
    thumbnail_url: null,
    description: "Samsung's flagship with Galaxy AI features and titanium frame.",
    common_issues: ["Screen cracked", "USB-C port loose", "Battery draining fast", "Back glass cracked", "Fingerprint sensor not working"],
    is_popular: true,
  },
  {
    category_slug: "phones",
    slug: "samsung-galaxy-s23",
    name: "Samsung Galaxy S23",
    brand: "Samsung",
    model_year: 2023,
    model_file: null,
    thumbnail_url: null,
    description: "Samsung's Galaxy S23 with Snapdragon 8 Gen 2 and a refined camera system.",
    common_issues: ["Cracked screen", "Back glass broken", "Charging port issue", "Battery life poor", "Camera app crashing"],
    is_popular: false,
  },
  {
    category_slug: "phones",
    slug: "samsung-galaxy-s22",
    name: "Samsung Galaxy S22",
    brand: "Samsung",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Samsung Galaxy S22 with contour cut camera and Armor Aluminum frame.",
    common_issues: ["Screen damage", "Battery swelling", "USB-C port loose", "Speaker grille clogged", "Phantom touch issues"],
    is_popular: false,
  },
  {
    category_slug: "phones",
    slug: "google-pixel-8",
    name: "Google Pixel 8",
    brand: "Google",
    model_year: 2023,
    model_file: null,
    thumbnail_url: null,
    description: "Google's Pixel 8 with Tensor G3 chip and 7-year software support.",
    common_issues: ["Cracked screen", "Battery draining fast", "Overheating during calls", "USB-C port issues", "Rear camera module loose"],
    is_popular: false,
  },
  {
    category_slug: "phones",
    slug: "google-pixel-7",
    name: "Google Pixel 7",
    brand: "Google",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Google's Pixel 7 with Tensor G2 and an aluminum camera bar.",
    common_issues: ["Screen cracked", "Battery draining", "Speaker quiet", "Face unlock slow", "Charging port intermittent"],
    is_popular: false,
  },
  {
    category_slug: "phones",
    slug: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    model_year: 2024,
    model_file: null,
    thumbnail_url: null,
    description: "OnePlus 12 with Snapdragon 8 Gen 3 and 100W SUPERVOOC charging.",
    common_issues: ["Cracked screen", "Alert slider stuck", "Charging port damage", "Battery draining", "Back glass cracked"],
    is_popular: false,
  },
  {
    category_slug: "phones",
    slug: "motorola-edge-40",
    name: "Motorola Edge 40",
    brand: "Motorola",
    model_year: 2023,
    model_file: null,
    thumbnail_url: null,
    description: "Motorola Edge 40 with curved pOLED display and 68W TurboPower charging.",
    common_issues: ["Curved screen cracked", "USB-C port loose", "Battery draining fast", "Rear camera lens cracked"],
    is_popular: false,
  },

  // ── TV REMOTES ───────────────────────────────────────────────────
  {
    category_slug: "tv-remotes",
    slug: "samsung-smart-remote",
    name: "Samsung Smart TV Remote",
    brand: "Samsung",
    model_year: 2021,
    model_file: null,
    thumbnail_url: null,
    description: "Samsung's slim solar and RF-powered Smart Remote for QLED and Neo QLED TVs.",
    common_issues: ["Buttons not responding", "Solar charging not working", "Battery contacts corroded", "Remote not pairing", "Voice command button broken"],
    is_popular: false,
  },
  {
    category_slug: "tv-remotes",
    slug: "lg-magic-remote",
    name: "LG Magic Remote",
    brand: "LG",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "LG's pointer-based remote with voice control and scroll wheel.",
    common_issues: ["Pointer not working", "Scroll wheel stuck", "Buttons sticking", "Battery drain", "Pairing lost after TV reset"],
    is_popular: false,
  },
  {
    category_slug: "tv-remotes",
    slug: "sony-bravia-remote",
    name: "Sony Bravia Remote",
    brand: "Sony",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Sony's Bravia XR remote with backlighting and Bluetooth.",
    common_issues: ["Backlight not working", "Google Assistant button broken", "Battery contacts dirty", "Bluetooth pairing fails", "Volume button stuck"],
    is_popular: false,
  },
  {
    category_slug: "tv-remotes",
    slug: "roku-voice-remote",
    name: "Roku Voice Remote Pro",
    brand: "Roku",
    model_year: 2021,
    model_file: null,
    thumbnail_url: null,
    description: "Roku's rechargeable voice remote with headphone jack and private listening.",
    common_issues: ["Voice button not activating", "Private listening crackling", "USB-C charge port intermittent", "Pairing drops", "Private channel button broken"],
    is_popular: false,
  },
  {
    category_slug: "tv-remotes",
    slug: "amazon-fire-tv-remote",
    name: "Amazon Fire TV Remote",
    brand: "Amazon",
    model_year: 2021,
    model_file: null,
    thumbnail_url: null,
    description: "Amazon's Alexa voice remote for Fire TV Stick.",
    common_issues: ["Alexa button not working", "Battery drain", "Pairing issues", "Navigation ring stuck", "Power button broken"],
    is_popular: false,
  },
  {
    category_slug: "tv-remotes",
    slug: "apple-tv-siri-remote",
    name: "Apple TV Siri Remote (2nd Gen)",
    brand: "Apple",
    model_year: 2021,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's redesigned Siri Remote with a clickpad and USB-C charging.",
    common_issues: ["Clickpad unresponsive", "USB-C port damaged", "Siri button not registering", "Battery draining fast", "Remote losing sync"],
    is_popular: false,
  },
  {
    category_slug: "tv-remotes",
    slug: "vizio-smartcast-remote",
    name: "Vizio SmartCast Remote",
    brand: "Vizio",
    model_year: 2020,
    model_file: null,
    thumbnail_url: null,
    description: "Vizio's backlit remote with dedicated streaming app buttons.",
    common_issues: ["App shortcut buttons broken", "Backlight dim", "Battery corrosion", "IR signal weak", "Input button sticking"],
    is_popular: false,
  },

  // ── ELECTRONICS ─────────────────────────────────────────────────
  {
    category_slug: "electronics",
    slug: "macbook-pro-m3",
    name: "MacBook Pro (M3, 2023)",
    brand: "Apple",
    model_year: 2023,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's 14\" or 16\" MacBook Pro with M3 chip, Liquid Retina XDR, and MagSafe 3.",
    common_issues: ["Battery swelling", "Screen backlight flickering", "MagSafe port not charging", "Keyboard key stuck", "Fan loud", "Trackpad click not registering"],
    is_popular: true,
  },
  {
    category_slug: "electronics",
    slug: "macbook-pro-m2",
    name: "MacBook Pro (M2, 2022)",
    brand: "Apple",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's MacBook Pro with M2 chip and notched display.",
    common_issues: ["Battery capacity reduced", "Keyboard key unresponsive", "MagSafe not connecting", "Screen cracks", "USB-C port damage"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "macbook-pro-m1",
    name: "MacBook Pro (M1, 2020)",
    brand: "Apple",
    model_year: 2020,
    model_file: null,
    thumbnail_url: null,
    description: "The first MacBook Pro with Apple Silicon M1 chip.",
    common_issues: ["Battery swelling", "USB-C port damage", "Display cable issue", "Keyboard key stuck", "Trackpad cracking"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "ipad-pro",
    name: "iPad Pro (M2, 2022)",
    brand: "Apple",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's iPad Pro with M2 chip, ProMotion display, and USB-C Thunderbolt.",
    common_issues: ["Screen cracked", "Apple Pencil not connecting", "USB-C port debris", "Battery draining fast", "Smart Connector pins corroded"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "ipad-air",
    name: "iPad Air (5th Gen)",
    brand: "Apple",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's iPad Air with M1 chip and USB-C.",
    common_issues: ["Cracked screen", "Touch ID button unresponsive", "Battery draining", "USB-C port loose", "Smart Connector not working"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "airpods-pro-2nd-gen",
    name: "AirPods Pro (2nd Gen)",
    brand: "Apple",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's AirPods Pro with active noise cancellation, Adaptive Transparency, and MagSafe case.",
    common_issues: ["ANC not working", "One earbud not charging", "Stem touch not registering", "Case hinge loose", "Static noise in one ear"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "airpods-pro-1st-gen",
    name: "AirPods Pro (1st Gen)",
    brand: "Apple",
    model_year: 2019,
    model_file: null,
    thumbnail_url: null,
    description: "Apple's original AirPods Pro with noise cancellation.",
    common_issues: ["Crackling sound", "ANC cutting out", "Case not charging", "Earbud not detected", "Microphone muffled"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    model_year: 2022,
    model_file: null,
    thumbnail_url: null,
    description: "Sony's flagship over-ear noise cancelling headphones.",
    common_issues: ["Ear cup padding peeling", "ANC weak", "USB-C port loose", "Headband cracking", "Left/right imbalance", "Bluetooth dropout"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "nintendo-switch",
    name: "Nintendo Switch",
    brand: "Nintendo",
    model_year: 2017,
    model_file: null,
    thumbnail_url: null,
    description: "Nintendo's hybrid home/portable console.",
    common_issues: ["Joy-Con rail loose", "USB-C port not charging", "SD card slot not reading", "Dock not outputting HDMI", "Fan loud", "Screen cracked"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "ps5-console",
    name: "PlayStation 5",
    brand: "Sony",
    model_year: 2020,
    model_file: null,
    thumbnail_url: null,
    description: "Sony's PS5 home console with SSD and haptic DualSense controller.",
    common_issues: ["Disc drive not reading", "HDMI port damage", "USB-C port on front broken", "Fan loud", "Console not turning on", "Disc getting stuck"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "xbox-series-x",
    name: "Xbox Series X",
    brand: "Microsoft",
    model_year: 2020,
    model_file: null,
    thumbnail_url: null,
    description: "Microsoft's Xbox Series X home console.",
    common_issues: ["Disc drive loud", "HDMI port bent pins", "Power button not responding", "Expansion card slot issue", "Fan grinding"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "kindle-paperwhite",
    name: "Kindle Paperwhite (11th Gen)",
    brand: "Amazon",
    model_year: 2021,
    model_file: null,
    thumbnail_url: null,
    description: "Amazon's premium e-reader with adjustable warm light and 6.8\" display.",
    common_issues: ["Screen cracked", "USB-C not charging", "Battery draining fast", "Touchscreen unresponsive", "Waterproofing seal damaged"],
    is_popular: false,
  },
  {
    category_slug: "electronics",
    slug: "gopro-hero-12",
    name: "GoPro HERO12 Black",
    brand: "GoPro",
    model_year: 2023,
    model_file: null,
    thumbnail_url: null,
    description: "GoPro's action camera with HyperSmooth 6.0 stabilization.",
    common_issues: ["Lens fogging", "Battery door latch broken", "USB-C port loose", "Screen cracked", "Microphone muffled underwater", "Battery draining fast"],
    is_popular: false,
  },
];
